{
 "title": "Monitoramento RB",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "agent_name",
    "label": "Agent",
    "query": "{ \"find\": \"terms\", \"field\": \"agent.name\", \"query\": \"\"}"
   },
   {
    "name": "rule_level",
    "label": "Rule Level",
    "query": "{ \"find\": \"terms\", \"field\": \"rule.level\", \"query\": \"\"}"
   }
  ]
 },
 "panels": [
  { "type": "yesoreyeram-boomtheme-panel", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "gapit-htmlgraphics-panel",
   "gridPos": { "h": 13, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": {
    "reduceOptions": {
     "calcs": [
      "lastNotNull",
      "last",
      "firstNotNull",
      "first",
      "min",
      "max",
      "mean",
      "sum",
      "count",
      "range",
      "delta",
      "step",
      "diff",
      "logmin",
      "allIsZero",
      "allIsNull",
      "diffperc"
     ]
    }
   },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Usuários Logados" ],
       "text": "setAlias()"
      }
     ],
     "group": { "filter": "mikrotik" },
     "host": { "filter": "MK ROTASAT" },
     "item": { "filter": "Device: Temperature" },
     "itemTag": { "filter": "component: temperature" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Usuários Logados" ],
       "text": "setAlias()"
      }
     ],
     "group": { "filter": "mikrotik" },
     "host": { "filter": "MK ROTASAT" },
     "item": { "filter": "Disk-131072: Space utilization" },
     "itemTag": { "filter": "component: storage" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Usuários Logados" ],
       "text": "setAlias()"
      }
     ],
     "group": { "filter": "mikrotik" },
     "host": { "filter": "MK ROTASAT" },
     "item": {
      "filter": "Interface bridge1(BridgeLAN): Bits sent"
     },
     "itemTag": { "filter": "interface: bridge1" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Usuários Logados" ],
       "text": "setAlias()"
      }
     ],
     "group": { "filter": "mikrotik" },
     "host": { "filter": "MK ROTASAT" },
     "item": {
      "filter": "Interface bridge1(BridgeLAN): Bits received"
     },
     "itemTag": { "filter": "description: BridgeLAN" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Usuários Logados" ],
       "text": "setAlias()"
      }
     ],
     "group": { "filter": "mikrotik" },
     "host": { "filter": "MK ROTASAT" },
     "item": { "filter": "Uptime (hardware)" },
     "itemTag": { "filter": "component: system" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Usuários Logados" ],
       "text": "setAlias()"
      }
     ],
     "group": { "filter": "mikrotik" },
     "host": { "filter": "MK ROTASAT" },
     "item": { "filter": "Uptime (network)" },
     "itemTag": { "filter": "component: system" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Usuários Logados" ],
       "text": "setAlias()"
      }
     ],
     "group": { "filter": "mikrotik" },
     "host": { "filter": "MK ROTASAT" },
     "item": { "filter": "ICMP ping" },
     "itemTag": { "filter": "component: health" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Usuários Logados" ],
       "text": "setAlias()"
      }
     ],
     "group": { "filter": "mikrotik" },
     "host": { "filter": "MK ROTASAT" },
     "item": { "filter": "Memory utilization" },
     "itemTag": { "filter": "component: memory" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Usuários Logados" ],
       "text": "setAlias()"
      }
     ],
     "group": { "filter": "mikrotik" },
     "host": { "filter": "MK ROTASAT" },
     "item": { "filter": "#1: CPU utilization" },
     "itemTag": { "filter": "component: cpu" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Alertas Gerais",
   "type": "alexanderzobnin-zabbix-triggers-panel",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 1 },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "mikrotik" },
     "host": { "filter": "MK ROTASAT" },
     "item": { "filter": "" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "acknowledged": 2,
      "count": false,
      "disableDataAlignment": false,
      "hostProxy": false,
      "hostsInMaintenance": false,
      "limit": 1001,
      "minSeverity": 0,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "sortProblems": "default",
      "useTimeRange": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "showProblems": "problems",
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Analise de Log",
   "type": "logs",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 7 },
   "targets": [
    {
     "application": { "filter": "/.*/" },
     "evaltype": "0",
     "group": { "filter": "Servidores" },
     "host": { "filter": "dkic" },
     "item": { "filter": "" },
     "itemTag": { "filter": "Log SSH Servidor" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "options": {
    "content": "<div style=\"\n  font-size: 12px;\n  text-align: center;\n  letter-spacing: 3px;\n  text-shadow: 1px 1px 2px #000000;\n  border-radius: 30px 30px;\n   background: linear-gradient(100deg, ##ff8800, #E65100);\n  color: white;\n  font-family: 'Exo Semi-Bold', Roboto, sans-serif;\n  font-weight: bold;\n  position: absolute;\n  padding: 5px;\n\">\n\n</div>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 15 },
   "options": {
    "content": "<div style=\"\n  font-size: 12px;\n  text-align: center;\n  letter-spacing: 3px;\n  text-shadow: 1px 1px 2px #000000;\n  border-radius: 30px 30px;\n   background: linear-gradient(100deg, #ff8800, #E65100);\n  color: white;\n  font-family: 'Exo Semi-Bold', Roboto, sans-serif;\n  font-weight: bold;\n  position: absolute;\n  padding: 5px;\n\">\n  CPU\n</div>"
   }
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 3, "y": 15 },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "mikrotik" },
     "host": { "filter": "MK ROTASAT" },
     "item": { "filter": "#1: CPU utilization" },
     "itemTag": { "filter": "component: cpu" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 15 },
   "options": {
    "content": "<div style=\"\n  font-size: 12px;\n  text-align: center;\n  letter-spacing: 3px;\n  text-shadow: 1px 1px 2px #000000;\n  border-radius: 30px 30px;\n   background: linear-gradient(100deg, #ff8800, #E65100);\n  color: white;\n  font-family: 'Exo Semi-Bold', Roboto, sans-serif;\n  font-weight: bold;\n  position: absolute;\n  padding: 5px;\n\">\n  Temperatura\n</div>"
   }
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 15 },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "mikrotik" },
     "host": { "filter": "MK ROTASAT" },
     "item": { "filter": "Device: Temperature" },
     "itemTag": { "filter": "component: temperature" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 17 },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "mikrotik" },
     "host": { "filter": "MK ROTASAT" },
     "item": { "filter": "#1: CPU utilization" },
     "itemTag": { "filter": "component: cpu" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 17 },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "mikrotik" },
     "host": { "filter": "MK ROTASAT" },
     "item": { "filter": "Device: Temperature" },
     "itemTag": { "filter": "component: temperature" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "options": {
    "content": "<div style=\"\n  font-size: 12px;\n  text-align: center;\n  letter-spacing: 3px;\n  text-shadow: 1px 1px 2px #000000;\n  border-radius: 30px 30px;\n   background: linear-gradient(100deg, ##ff8800, #E65100);\n  color: white;\n  font-family: 'Exo Semi-Bold', Roboto, sans-serif;\n  font-weight: bold;\n  position: absolute;\n  padding: 5px;\n\">\n\n</div>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 22 },
   "options": {
    "content": "<div style=\"\n  font-size: 12px;\n  text-align: center;\n  letter-spacing: 3px;\n  text-shadow: 1px 1px 2px #000000;\n  border-radius: 30px 30px;\n   background: linear-gradient(100deg, #ff8800, #E65100);\n  color: white;\n  font-family: 'Exo Semi-Bold', Roboto, sans-serif;\n  font-weight: bold;\n  position: absolute;\n  padding: 5px;\n\">\n  Memória\n</div>"
   }
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 3, "y": 22 },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "mikrotik" },
     "host": { "filter": "MK ROTASAT" },
     "item": { "filter": "Memory utilization" },
     "itemTag": { "filter": "component: memory" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 22 },
   "options": {
    "content": "<div style=\"\n  font-size: 12px;\n  text-align: center;\n  letter-spacing: 3px;\n  text-shadow: 1px 1px 2px #000000;\n  border-radius: 30px 30px;\n   background: linear-gradient(100deg, #ff8800, #E65100);\n  color: white;\n  font-family: 'Exo Semi-Bold', Roboto, sans-serif;\n  font-weight: bold;\n  position: absolute;\n  padding: 5px;\n\">\n  HD\n</div>"
   }
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 22 },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "mikrotik" },
     "host": { "filter": "MK ROTASAT" },
     "item": { "filter": "Disk-131072: Space utilization" },
     "itemTag": { "filter": "component: storage" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 24 },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "mikrotik" },
     "host": { "filter": "MK ROTASAT" },
     "item": { "filter": "Memory utilization" },
     "itemTag": { "filter": "component: memory" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 24 },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "mikrotik" },
     "host": { "filter": "MK ROTASAT" },
     "item": { "filter": "Disk-131072: Space utilization" },
     "itemTag": { "filter": "component: storage" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  { "type": "yesoreyeram-boomtheme-panel", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 23, "x": 0, "y": 29 },
   "options": {
    "content": "<div style=\"\n  font-size: 12px;\n  text-align: center;\n  letter-spacing: 3px;\n  text-shadow: 1px 1px 2px #000000;\n  border-radius: 30px 30px;\n   background: linear-gradient(100deg, ##ff8800, #E65100);\n  color: white;\n  font-family: 'Exo Semi-Bold', Roboto, sans-serif;\n  font-weight: bold;\n  position: absolute;\n  padding: 5px;\n\">\n\n</div>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 30 },
   "options": {
    "content": "<div style=\"\n  font-size: 15px;\n  text-align: center;\n  letter-spacing: 3px;\n  text-shadow: 1px 1px 2px #000000;\n  border-radius: 30px 30px;\n   background: linear-gradient(100deg, #ff8800, #E65100);\n  color: white;\n  font-family: 'Exo Semi-Bold', Roboto, sans-serif;\n  font-weight: bold;\n  position: absolute;\n  padding: 5px;\n\">\n Tráfego\n</div>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 32 },
   "options": {
    "content": "<div style=\"\n  font-size: 12px;\n  text-align: center;\n  letter-spacing: 3px;\n  text-shadow: 1px 1px 2px #000000;\n  border-radius: 30px 30px;\n   background: linear-gradient(100deg, #ff8800, #E65100);\n  color: white;\n  font-family: 'Exo Semi-Bold', Roboto, sans-serif;\n  font-weight: bold;\n  position: absolute;\n  padding: 5px;\n\">\n  Histórico Bridge 1 Download\n</div>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 32 },
   "options": {
    "content": "<div style=\"\n  font-size: 12px;\n  text-align: center;\n  letter-spacing: 3px;\n  text-shadow: 1px 1px 2px #000000;\n  border-radius: 30px 30px;\n   background: linear-gradient(100deg, #ff8800, #E65100);\n  color: white;\n  font-family: 'Exo Semi-Bold', Roboto, sans-serif;\n  font-weight: bold;\n  position: absolute;\n  padding: 5px;\n\">\n  Histórico Bridge 1 Upload\n</div>"
   }
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "mikrotik" },
     "host": { "filter": "MK ROTASAT" },
     "item": {
      "filter": "Interface bridge1(BridgeLAN): Bits received"
     },
     "itemTag": { "filter": "description: BridgeLAN" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "mikrotik" },
     "host": { "filter": "MK ROTASAT" },
     "item": {
      "filter": "Interface bridge1(BridgeLAN): Bits sent"
     },
     "itemTag": { "filter": "description: BridgeLAN" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 6, "x": 1, "y": 42 },
   "options": {
    "content": "<div style=\"\n  font-size: 12px;\n  text-align: center;\n  letter-spacing: 3px;\n  text-shadow: 1px 1px 2px #000000;\n  border-radius: 30px 30px;\n   background: linear-gradient(100deg, #ff8800, #E65100);\n  color: white;\n  font-family: 'Exo Semi-Bold', Roboto, sans-serif;\n  font-weight: bold;\n  position: absolute;\n  padding: 5px;\n\">\n  Histórico Link Principal\n</div>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 7, "x": 8, "y": 42 },
   "options": {
    "content": "<div style=\"\n  font-size: 12px;\n  text-align: center;\n  letter-spacing: 3px;\n  text-shadow: 1px 1px 2px #000000;\n  border-radius: 30px 30px;\n   background: linear-gradient(100deg, #ff8800, #E65100);\n  color: white;\n  font-family: 'Exo Semi-Bold', Roboto, sans-serif;\n  font-weight: bold;\n  position: absolute;\n  padding: 5px;\n\">\n  Histórico Link Backup\n</div>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 7, "x": 16, "y": 42 },
   "options": {
    "content": "<div style=\"\n  font-size: 12px;\n  text-align: center;\n  letter-spacing: 3px;\n  text-shadow: 1px 1px 2px #000000;\n  border-radius: 30px 30px;\n   background: linear-gradient(100deg, #ff8800, #E65100);\n  color: white;\n  font-family: 'Exo Semi-Bold', Roboto, sans-serif;\n  font-weight: bold;\n  position: absolute;\n  padding: 5px;\n\">\n  Histórico Loss\n</div>"
   }
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 44 },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "mikrotik" },
     "host": { "filter": "MK ROTASAT" },
     "item": {
      "filter": "Interface pppoe-out1(): Bits received"
     },
     "itemTag": { "filter": "interface: pppoe-out1" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "mikrotik" },
     "host": { "filter": "MK ROTASAT" },
     "item": {
      "filter": "Interface pppoe-out1(): Bits sent"
     },
     "itemTag": { "filter": "interface: pppoe-out1" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 8, "y": 44 },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "mikrotik" },
     "host": { "filter": "MK ROTASAT" },
     "item": {
      "filter": "Interface pppoe-out2(): Bits sent"
     },
     "itemTag": { "filter": "interface: pppoe-out2" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "mikrotik" },
     "host": { "filter": "MK ROTASAT" },
     "item": {
      "filter": "Interface pppoe-out2(): Bits received"
     },
     "itemTag": { "filter": "interface: pppoe-out2" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 44 },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "mikrotik" },
     "host": { "filter": "MK ROTASAT" },
     "item": { "filter": "ICMP loss" },
     "itemTag": { "filter": "component: health" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 17, "x": 4, "y": 54 },
   "options": {
    "content": "<div style=\"\n  font-size: 12px;\n  text-align: center;\n  letter-spacing: 3px;\n  text-shadow: 1px 1px 2px #000000;\n  border-radius: 30px 30px;\n   background: linear-gradient(100deg, #ff8800, #E65100);\n  color: white;\n  font-family: 'Exo Semi-Bold', Roboto, sans-serif;\n  font-weight: bold;\n  position: absolute;\n  padding: 5px;\n\">\n  Histórico Lâtencia\n</div>"
   }
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "mikrotik" },
     "host": { "filter": "MK ROTASAT" },
     "item": { "filter": "ICMP response time" },
     "itemTag": { "filter": "component: health" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 65 },
   "options": {
    "content": "<div style=\"\n  font-size: 15px;\n  text-align: center;\n  letter-spacing: 3px;\n  text-shadow: 1px 1px 2px #000000;\n  border-radius: 30px 30px;\n   background: linear-gradient(100deg, #ff8800, #E65100);\n  color: white;\n  font-family: 'Exo Semi-Bold', Roboto, sans-serif;\n  font-weight: bold;\n  position: absolute;\n  padding: 5px;\n\">\n  Histórico Tráfego Portas Mikrotik\n</div>"
   }
  },
  {
   "title": "Tráfego Portas Mikrotik",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 67 },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "mikrotik" },
     "host": { "filter": "MK ROTASAT" },
     "item": {
      "filter": "Interface ether1(LinkPrincipal): Bits received"
     },
     "itemTag": { "filter": "interface: ether1" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "mikrotik" },
     "host": { "filter": "MK ROTASAT" },
     "item": {
      "filter": "Interface ether2(LinkBackup): Bits received"
     },
     "itemTag": { "filter": "interface: ether2" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "mikrotik" },
     "host": { "filter": "MK ROTASAT" },
     "item": {
      "filter": "Interface ether3(LAN BRIDGE1): Bits received"
     },
     "itemTag": { "filter": "interface: ether3" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "mikrotik" },
     "host": { "filter": "MK ROTASAT" },
     "item": {
      "filter": "Interface ether4(LAN BRIDGE1): Bits received"
     },
     "itemTag": { "filter": "interface: ether4" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "mikrotik" },
     "host": { "filter": "MK ROTASAT" },
     "item": {
      "filter": "Interface ether5(LAN BRIDGE1): Bits received"
     },
     "itemTag": { "filter": "interface: ether5" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Tráfego Portas Mikrotik",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 67 },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "mikrotik" },
     "host": { "filter": "MK ROTASAT" },
     "item": {
      "filter": "Interface ether1(LinkPrincipal): Bits sent"
     },
     "itemTag": { "filter": "interface: ether1" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "mikrotik" },
     "host": { "filter": "MK ROTASAT" },
     "item": {
      "filter": "Interface ether2(LinkBackup): Bits sent"
     },
     "itemTag": { "filter": "interface: ether2" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "mikrotik" },
     "host": { "filter": "MK ROTASAT" },
     "item": {
      "filter": "Interface ether3(LAN BRIDGE1): Bits sent"
     },
     "itemTag": { "filter": "interface: ether3" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "mikrotik" },
     "host": { "filter": "MK ROTASAT" },
     "item": {
      "filter": "Interface ether4(LAN BRIDGE1): Bits sent"
     },
     "itemTag": { "filter": "interface: ether4" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "mikrotik" },
     "host": { "filter": "MK ROTASAT" },
     "item": {
      "filter": "Interface ether5(LAN BRIDGE1): Bits sent"
     },
     "itemTag": { "filter": "interface: ether5" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  }
 ]
}